//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.22 at 10:15:36 PM PST 
//


package binji.demo.data.xml.ovd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
/**
 * @author jesse keane
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ovd }
     * 
     */
    public Ovd createOvd() {
        return new Ovd();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video }
     * 
     */
    public binji.demo.data.xml.ovd.Video createVideo() {
        return new binji.demo.data.xml.ovd.Video();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.ViewingOptions }
     * 
     */
    public binji.demo.data.xml.ovd.Video.ViewingOptions createVideoViewingOptions() {
        return new binji.demo.data.xml.ovd.Video.ViewingOptions();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption }
     * 
     */
    public binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption createVideoViewingOptionsViewingOption() {
        return new binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption();
    }

    /**
     * Create an instance of {@link FullVideo }
     * 
     */
    public FullVideo createFullVideo() {
        return new FullVideo();
    }

    /**
     * Create an instance of {@link FullVideo.ViewingOptions }
     * 
     */
    public FullVideo.ViewingOptions createFullVideoViewingOptions() {
        return new FullVideo.ViewingOptions();
    }

    /**
     * Create an instance of {@link FullVideo.ViewingOptions.ViewingOption }
     * 
     */
    public FullVideo.ViewingOptions.ViewingOption createFullVideoViewingOptionsViewingOption() {
        return new FullVideo.ViewingOptions.ViewingOption();
    }

    /**
     * Create an instance of {@link MultipleUrls }
     * 
     */
    public MultipleUrls createMultipleUrls() {
        return new MultipleUrls();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports }
     * 
     */
    public Ovd.OnlineSports createOvdOnlineSports() {
        return new Ovd.OnlineSports();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports.Sports }
     * 
     */
    public Ovd.OnlineSports.Sports createOvdOnlineSportsSports() {
        return new Ovd.OnlineSports.Sports();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports.Sports.Sport }
     * 
     */
    public Ovd.OnlineSports.Sports.Sport createOvdOnlineSportsSportsSport() {
        return new Ovd.OnlineSports.Sports.Sport();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports.Sports.Sport.SportsEvent }
     * 
     */
    public Ovd.OnlineSports.Sports.Sport.SportsEvent createOvdOnlineSportsSportsSportSportsEvent() {
        return new Ovd.OnlineSports.Sports.Sport.SportsEvent();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSpecials }
     * 
     */
    public Ovd.OnlineSpecials createOvdOnlineSpecials() {
        return new Ovd.OnlineSpecials();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSpecials.Special }
     * 
     */
    public Ovd.OnlineSpecials.Special createOvdOnlineSpecialsSpecial() {
        return new Ovd.OnlineSpecials.Special();
    }

    /**
     * Create an instance of {@link Ovd.OnlineMovies }
     * 
     */
    public Ovd.OnlineMovies createOvdOnlineMovies() {
        return new Ovd.OnlineMovies();
    }

    /**
     * Create an instance of {@link Ovd.OnlineMovies.Movie }
     * 
     */
    public Ovd.OnlineMovies.Movie createOvdOnlineMoviesMovie() {
        return new Ovd.OnlineMovies.Movie();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv }
     * 
     */
    public Ovd.OnlineTv createOvdOnlineTv() {
        return new Ovd.OnlineTv();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series }
     * 
     */
    public Ovd.OnlineTv.Series createOvdOnlineTvSeries() {
        return new Ovd.OnlineTv.Series();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Episodes }
     * 
     */
    public Ovd.OnlineTv.Series.Episodes createOvdOnlineTvSeriesEpisodes() {
        return new Ovd.OnlineTv.Series.Episodes();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Episodes.Episode }
     * 
     */
    public Ovd.OnlineTv.Series.Episodes.Episode createOvdOnlineTvSeriesEpisodesEpisode() {
        return new Ovd.OnlineTv.Series.Episodes.Episode();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons createOvdOnlineTvSeriesSeasons() {
        return new Ovd.OnlineTv.Series.Seasons();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season createOvdOnlineTvSeriesSeasonsSeason() {
        return new Ovd.OnlineTv.Series.Seasons.Season();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages createOvdOnlineTvSeriesSeasonsSeasonSeasonPages() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPage() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageViewingOptions() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageViewingOptionsViewingOption() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.SeriesPages }
     * 
     */
    public Ovd.OnlineTv.Series.SeriesPages createOvdOnlineTvSeriesSeriesPages() {
        return new Ovd.OnlineTv.Series.SeriesPages();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Host }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Host createVideoHost() {
        return new binji.demo.data.xml.ovd.Video.Host();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Title }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Title createVideoTitle() {
        return new binji.demo.data.xml.ovd.Video.Title();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Duration }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Duration createVideoDuration() {
        return new binji.demo.data.xml.ovd.Video.Duration();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Description }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Description createVideoDescription() {
        return new binji.demo.data.xml.ovd.Video.Description();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.SeasonNumber }
     * 
     */
    public binji.demo.data.xml.ovd.Video.SeasonNumber createVideoSeasonNumber() {
        return new binji.demo.data.xml.ovd.Video.SeasonNumber();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Image }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Image createVideoImage() {
        return new binji.demo.data.xml.ovd.Video.Image();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Type }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Type createVideoType() {
        return new binji.demo.data.xml.ovd.Video.Type();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.Rating }
     * 
     */
    public binji.demo.data.xml.ovd.Video.Rating createVideoRating() {
        return new binji.demo.data.xml.ovd.Video.Rating();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Price }
     * 
     */
    public binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Price createVideoViewingOptionsViewingOptionPrice() {
        return new binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Price();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd._Video.ViewingOptions.ViewingOption.Video }
     * 
     */
    public binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption._Video createVideoViewingOptionsViewingOptionVideo() {
        return new binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption._Video();
    }

    /**
     * Create an instance of {@link binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Audio }
     * 
     */
    public binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Audio createVideoViewingOptionsViewingOptionAudio() {
        return new binji.demo.data.xml.ovd.Video.ViewingOptions.ViewingOption.Audio();
    }

    /**
     * Create an instance of {@link FullVideo.Host }
     * 
     */
    public FullVideo.Host createFullVideoHost() {
        return new FullVideo.Host();
    }

    /**
     * Create an instance of {@link FullVideo.Title }
     * 
     */
    public FullVideo.Title createFullVideoTitle() {
        return new FullVideo.Title();
    }

    /**
     * Create an instance of {@link FullVideo.Duration }
     * 
     */
    public FullVideo.Duration createFullVideoDuration() {
        return new FullVideo.Duration();
    }

    /**
     * Create an instance of {@link FullVideo.Description }
     * 
     */
    public FullVideo.Description createFullVideoDescription() {
        return new FullVideo.Description();
    }

    /**
     * Create an instance of {@link FullVideo.SeasonNumber }
     * 
     */
    public FullVideo.SeasonNumber createFullVideoSeasonNumber() {
        return new FullVideo.SeasonNumber();
    }

    /**
     * Create an instance of {@link FullVideo.Image }
     * 
     */
    public FullVideo.Image createFullVideoImage() {
        return new FullVideo.Image();
    }

    /**
     * Create an instance of {@link FullVideo.Type }
     * 
     */
    public FullVideo.Type createFullVideoType() {
        return new FullVideo.Type();
    }

    /**
     * Create an instance of {@link FullVideo.Rating }
     * 
     */
    public FullVideo.Rating createFullVideoRating() {
        return new FullVideo.Rating();
    }

    /**
     * Create an instance of {@link FullVideo.ViewingOptions.ViewingOption.Price }
     * 
     */
    public FullVideo.ViewingOptions.ViewingOption.Price createFullVideoViewingOptionsViewingOptionPrice() {
        return new FullVideo.ViewingOptions.ViewingOption.Price();
    }

    /**
     * Create an instance of {@link FullVideo.ViewingOptions.ViewingOption.Video }
     * 
     */
    public FullVideo.ViewingOptions.ViewingOption.Video createFullVideoViewingOptionsViewingOptionVideo() {
        return new FullVideo.ViewingOptions.ViewingOption.Video();
    }

    /**
     * Create an instance of {@link FullVideo.ViewingOptions.ViewingOption.Audio }
     * 
     */
    public FullVideo.ViewingOptions.ViewingOption.Audio createFullVideoViewingOptionsViewingOptionAudio() {
        return new FullVideo.ViewingOptions.ViewingOption.Audio();
    }

    /**
     * Create an instance of {@link MultipleUrls.Url }
     * 
     */
    public MultipleUrls.Url createMultipleUrlsUrl() {
        return new MultipleUrls.Url();
    }

    /**
     * Create an instance of {@link Data.Datum }
     * 
     */
    public Data.Datum createDataDatum() {
        return new Data.Datum();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports.Sports.Sport.SportsEvent.Videos }
     * 
     */
    public Ovd.OnlineSports.Sports.Sport.SportsEvent.Videos createOvdOnlineSportsSportsSportSportsEventVideos() {
        return new Ovd.OnlineSports.Sports.Sport.SportsEvent.Videos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSports.Sports.Sport.SportsEvent.RelatedVideos }
     * 
     */
    public Ovd.OnlineSports.Sports.Sport.SportsEvent.RelatedVideos createOvdOnlineSportsSportsSportSportsEventRelatedVideos() {
        return new Ovd.OnlineSports.Sports.Sport.SportsEvent.RelatedVideos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSpecials.Special.Videos }
     * 
     */
    public Ovd.OnlineSpecials.Special.Videos createOvdOnlineSpecialsSpecialVideos() {
        return new Ovd.OnlineSpecials.Special.Videos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineSpecials.Special.RelatedVideos }
     * 
     */
    public Ovd.OnlineSpecials.Special.RelatedVideos createOvdOnlineSpecialsSpecialRelatedVideos() {
        return new Ovd.OnlineSpecials.Special.RelatedVideos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineMovies.Movie.Videos }
     * 
     */
    public Ovd.OnlineMovies.Movie.Videos createOvdOnlineMoviesMovieVideos() {
        return new Ovd.OnlineMovies.Movie.Videos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineMovies.Movie.RelatedVideos }
     * 
     */
    public Ovd.OnlineMovies.Movie.RelatedVideos createOvdOnlineMoviesMovieRelatedVideos() {
        return new Ovd.OnlineMovies.Movie.RelatedVideos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.RelatedVideos }
     * 
     */
    public Ovd.OnlineTv.Series.RelatedVideos createOvdOnlineTvSeriesRelatedVideos() {
        return new Ovd.OnlineTv.Series.RelatedVideos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Episodes.Episode.Videos }
     * 
     */
    public Ovd.OnlineTv.Series.Episodes.Episode.Videos createOvdOnlineTvSeriesEpisodesEpisodeVideos() {
        return new Ovd.OnlineTv.Series.Episodes.Episode.Videos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Episodes.Episode.RelatedVideos }
     * 
     */
    public Ovd.OnlineTv.Series.Episodes.Episode.RelatedVideos createOvdOnlineTvSeriesEpisodesEpisodeRelatedVideos() {
        return new Ovd.OnlineTv.Series.Episodes.Episode.RelatedVideos();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.Host }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.Host createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageHost() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.Host();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Price }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Price createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageViewingOptionsViewingOptionPrice() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Price();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Video }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Video createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageViewingOptionsViewingOptionVideo() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Video();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Audio }
     * 
     */
    public Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Audio createOvdOnlineTvSeriesSeasonsSeasonSeasonPagesSeasonPageViewingOptionsViewingOptionAudio() {
        return new Ovd.OnlineTv.Series.Seasons.Season.SeasonPages.SeasonPage.ViewingOptions.ViewingOption.Audio();
    }

    /**
     * Create an instance of {@link Ovd.OnlineTv.Series.SeriesPages.Host }
     * 
     */
    public Ovd.OnlineTv.Series.SeriesPages.Host createOvdOnlineTvSeriesSeriesPagesHost() {
        return new Ovd.OnlineTv.Series.SeriesPages.Host();
    }

}
